# Generated by Django 3.1.7 on 2021-06-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('contect_number', models.CharField(max_length=15)),
                ('email_address', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
