# Generated by Django 3.1.7 on 2021-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='item2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='false', max_length=50)),
                ('price', models.CharField(default='false', max_length=50)),
                ('description', models.CharField(default='false', max_length=500)),
                ('amazonlink', models.CharField(default='false', max_length=500)),
                ('flipcart', models.CharField(default='false', max_length=500)),
                ('imageurl', models.CharField(default='false', max_length=500)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
