# Generated by Django 3.1.7 on 2021-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item2',
            name='amazonlink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item2',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item2',
            name='flipcart',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item2',
            name='imageurl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item2',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item2',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
