# Generated by Django 3.1.7 on 2021-06-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210615_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phonenumber', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('massage', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
